---
title: "Fotmob"
author: "Fabrizio Cominetti"
date: '2022-08-14'
output: html_document
---

```{r}
library(worldfootballR)
library(dplyr)
library(tidyr)
```

Get data from Serie A round 1 matches

```{r}
fotmob_matches <- c(3919071, 3919073, 3919077, 3919072, 3919075, 3919074)
match_details <- fotmob_get_match_details(fotmob_matches)
dplyr::glimpse(match_details)
```

```{r}
mil_udi <- match_details[[15]][[1]]
head(mil_udi)
```


```{r}
write.csv(mil_udi,"C:\\Users\\FC\\Documents\\Projects\\football-analytics\\xG-lollipop\\data\\serieA-mil_udi.csv", row.names = TRUE)
```

```{r}
sam_ata <- match_details[[15]][[2]]
lec_int <- match_details[[15]][[3]]
mon_tor <- match_details[[15]][[4]]
fio_cre <- match_details[[15]][[5]]
laz_bol <- match_details[[15]][[6]]
```

```{r}
write.csv(sam_ata,"C:\\Users\\FC\\Documents\\Projects\\football-analytics\\xG-lollipop\\data\\serieA-sam_ata.csv", row.names = TRUE)
write.csv(lec_int,"C:\\Users\\FC\\Documents\\Projects\\football-analytics\\xG-lollipop\\data\\serieA-lec_int.csv", row.names = TRUE)
write.csv(mon_tor,"C:\\Users\\FC\\Documents\\Projects\\football-analytics\\xG-lollipop\\data\\serieA-mon_tor.csv", row.names = TRUE)
write.csv(fio_cre,"C:\\Users\\FC\\Documents\\Projects\\football-analytics\\xG-lollipop\\data\\serieA-fio_cre.csv", row.names = TRUE)
write.csv(laz_bol,"C:\\Users\\FC\\Documents\\Projects\\football-analytics\\xG-lollipop\\data\\serieA-laz_bol.csv", row.names = TRUE)
```

